# Robot Configuration Parameters
TrajectoryPlannerROS:
    max_vel_x: 0.3
    min_vel_x: 0.0

    max_vel_y: 0.0  # diff drive robot , not set by default
    min_vel_y: 0.0  # diff drive robot , not set by default

    acc_lim_x: 1.25
    acc_lim_y: 1.25
    acc_lim_th: 1.6
   
    max_rotational_vel: 1.2
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.1
    holonomic_robot: true

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.3  #default 0.1
    yaw_goal_tolerance: 0.3 #default 0.1

    # Forward Simulation Parameters
    sim_time: 5.0 #1.7
    sim_granularity: 0.025
    vx_samples: 30  #10
    vy_samples: 30  #10
    vtheta_samples: 20 #10

    # Trajectory Scoring Parameters
    goal_distance_bias: 1.0 #0.8
    path_distance_bias: 1.0 #0.6
    occdist_scale: 100.0  # 0.01
    heading_lookahead: 0.325
    dwa: false

    # Oscillation Prevention Parameters
oscillation_reset_dist: 0.05 #0.01